[package]
name = "rethnet_rpc_server"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.13", default-features = false, features = ["ahash"] }
rethnet_eth = { version = "0.1.0-dev", path = "../rethnet_eth", features = ["serde"] }
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.89" }

[dev-dependencies]
bytes = { version = "1.2.1", default-features = false }
